on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main
    paths:
      - 'backend/**'

env:
  REG_NAME: "acrinfobi22210.azurecr.io" # Nom du registy
  IMAGE_NAME: "backend-TM" # Nom de votre image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REG_NAME }}
          username: acrinfobi22210
          password: ${{ secrets.password }}
          
      # Build de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REG_NAME }}}}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # Push vers la registry
      - name: Push Docker image
        run: |
          docker push ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
